### ISSUE TITLE
所以 Figure 5.6 到底是什么图

### ISSUE THREAD

**Issue by LHertz** [ShusenTang/Deep-Learning-with-PyTorch-Chinese#9]
首先非常感谢作者的良心翻译和细心注解，大佬辛苦了~

所以有人知道 5.1.2 节中官方放错的图片 5.6 长什么样子吗，想象力太差，单凭文字描述想象不出来。。。。

**Comment by ShusenTang** [comment]
不知道。。我甚至去看了[完整版对应章节](https://livebook.manning.com/book/deep-learning-with-pytorch/chapter-6/section-6-1-1?origin=product-toc)但是一直加载不出来，你试试

**Comment by LHertz** [comment]
啊哈哈哈哈我刚想回来把这个问题关掉，没想到您这么快就回复了，我也是刚从完整版回来，我这加载出来了，在完整版的 [6.1.2 节](https://livebook.manning.com/book/deep-learning-with-pytorch/chapter-6/v-12/54)中的 [figure 6.5](https://dpzbhybb2pdcj.cloudfront.net/stevens2/v-12/Figures/weight_bias.png)，看了下应该是对得上的，要不您验证一下？

**Comment by ShusenTang** [comment]
我加载不出来，麻烦你发我邮箱吧

**Comment by LHertz** [comment]
已发送，请查收

**Comment by ShusenTang** [comment]
感谢，已更新
